# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Example_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example_iOS
  pod 'MarkdownUI', :path => '../../'
  pod 'cmark_gfm', :git => 'https://github.com/ghostcrying/swift-cmark.git', :tag => '0.0.4'

end
